#!/usr/bin/env ruby


option = ARGV[0]

LIST = "list"

def enlist()
	File.open(LIST, "r").each_line { |l|
			puts l
	}
end

case option
when "-h"
  puts "========== YOUR AUTO BROWSER =========== "
  puts 
  puts "./yab add [url]    ... add bookmarks"
  puts "./yab list  ...show current bookmarks"
  puts "./yab play  ... play the first of the bookmark list (then the link"
  puts "                played located at the last of the entire stack"
when "add"  
  f = File.open(LIST, "a")
  f.puts ARGV[1]
  f.close
  enlist
when "list"
  enlist
when "play"
  lines = File.open(LIST, "r").each_line.to_a 
  require 'launchy'
	Launchy.open(lines[0].strip) 
  f = File.open(LIST,"w")
  lines[1..-1].push(lines[0]).each { |l| 
    f.puts l
  } 
  f.close
end
 


