#!/usr/bin/env ruby


option = ARGV[0]

LIST = "resource/list"

def enlist(file)
	File.open(file, "r").each_line { |l|
			puts l
	}
end

def getFile(op)
  i = 1
  puts op
  case op
  when "add"
    i = 2
  when "play"
  end
	file = LIST
  if ARGV.size > i 
  file = "resource/"+ARGV[i]
  end
  if (File.file?(file) == false)
   f = File.new file, "w"
   f.close
  end
  file
end

def getOp()
	op = "resource/list"
	if ARGV.size > 1 
		op = "resource/#{ARGV[1]}"
	end
  op
end

case option
when "-h"
  puts "========== YOUR AUTO BROWSER =========== "
  puts 
  puts "./yab add [url]    ... add bookmarks"
  puts "./yab list  ...show current bookmarks"
  puts "./yab play  ... play the first of the bookmark list (then the link"
  puts "                played located at the last of the entire stack"
when "add"  
  f = File.open(getFile("add"), "a")
  f.puts ARGV[1]
  f.close
when "list"
  #op = "resource/list"
  #if ARGV.size > 1 
  #  op = "resource/#{ARGV[1]}"
  #end
  op = getOp
  enlist(op)
when "play"
  file = getFile("play")
  lines = File.open(file, "r").each_line.to_a 
  require 'launchy'
	Launchy.open(lines[0].strip) 
  f = File.open(file, "w")
  lines[1..-1].push(lines[0]).each { |l| 
    f.puts l
  } 
  f.close
when "select"
	file = "resource/#{ARGV[1]}"
	arr = File.open(file, "r").each_line.to_a 
	i = ARGV[2].to_i
	require 'launchy'
	Launchy.open(arr[i].strip) 
end
 


